#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Oct 19 06:48:04 +0000 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 49b029c17f5b42e6bb9981a43b82472a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot thermostat_simulation_behav xil_defaultlib.thermostat_simulation -log elaborate.log"
xelab -wto 49b029c17f5b42e6bb9981a43b82472a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot thermostat_simulation_behav xil_defaultlib.thermostat_simulation -log elaborate.log

